{
 "title": "Airsonic Music Analytics",
 "description": "Airsonic-Advanced container dashboard on docker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "What IP is active",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (ip) (\n  count_over_time(\n    {container=\"airsonic-advanced\"} \n    | regexp `StreamController\\s+:\\s+(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+):`\n    | ip != \"\"\n    [1m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Playback timeline",
   "type": "timeseries",
   "description": "Playback activity over time",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(album, song) (\n  count_over_time(\n    {container=\"airsonic-advanced\"} \n    |= \"StreamController\"\n    |= \"listening to\"\n    | regexp `listening to \\(\\d+\\) - (?P<album>[^/]+)/\\d+ - (?P<song>[^.]+)\\.mp3`\n    [$__auto]\n  )\n)"
    }
   ]
  },
  {
   "title": "Top artists",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(artist) (\n  count_over_time(\n    {container=\"airsonic-advanced\"} \n    |= \"CacheConfiguration$CacheLogger\"\n    |= \"[album]\"\n    | regexp `Cache Key: (?P<artist>[^/]+)/\\[album\\]/`\n    | artist != \"\"\n    [$__auto]\n  )\n)"
    }
   ]
  },
  {
   "title": "Airsonic Restarts",
   "type": "stat",
   "description": "Too many restarts and it goes red with concern.",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"airsonic-advanced\"} |= \"Starting Application\" [24h])"
    }
   ]
  },
  {
   "title": "Logs for user and album",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"airsonic-advanced\"} \n|~ \"StreamController.+listening to|Cache Key:.+\\\\[album\\\\].+CREATED\"\n| regexp `(?P<user>\\w+) listening to \\((?P<year>\\d+)\\) - (?P<album>[^/]+)/\\d+ - (?P<song>[^.]+)\\.mp3|Cache Key: (?P<artist>[^/]+)/\\[album\\]/\\((?P<cache_year>\\d+)\\) - (?P<cache_album>[^-]+)`\n| line_format \"{{ .timestamp }} | {{ if .user }}USER: {{.user}} is listening to: {{.album}} ({{.year}}) - {{.song}}{{ else }} {{.artist}} - {{.cache_album}} ({{.cache_year}}){{ end }}\""
    }
   ]
  }
 ]
}