{
 "title": "LyrionMusicServer Playback Analytics",
 "description": "Grafana Dashboard for LyrionMusicServer",
 "tags": [ "mac" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Music playback timeline by device",
   "type": "state-timeline",
   "description": "TimeliLYRION FIXEDlaying music",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(mac) (count_over_time({container=~\"(?i)(lyrionmusicserver|lms)\"} |= \"is playing music\" | regexp `(?P<mac>[a-f0-9:]+) is playing music` [$__auto]) > 0)"
    }
   ]
  },
  {
   "title": "Playback timeline",
   "type": "timeseries",
   "description": "Playback activity over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(artist, song) (count_over_time({container=~\"(?i)(lyrionmusicserver|lms)\"} |= \"currently playing\" [$__auto]))",
     "legendFormat": "{{song}} - {{artist}}"
    }
   ]
  },
  {
   "title": "Top artists",
   "type": "piechart",
   "description": "Most frequently played artists/bands",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, \n  sum by(artist) (\n    count_over_time({container=~\"(?i)(lyrionmusicserver|lms)\"} \n      |= \"currently playing\" \n      | regexp `currently playing \"[^\\t]+\\t[^\\t]+\\t(?P<artist>[^\\t]+)\\t`\n      | artist != \"\"\n    [$__auto])\n  )\n)"
    }
   ]
  },
  {
   "title": "Top streams",
   "type": "piechart",
   "description": "Most frequently played artists/bands",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, \n  sum by(station) (\n    count_over_time({container=~\"(?i)(lyrionmusicserver|lms)\"} \n      |= \"currently playing\" \n      |= \"http\"\n      | regexp `currently playing \"[^\\t]+\\t+(?P<url>https?://[^\\s]+)`\n      | label_format station=\"{{regexReplaceAll \\\"^https?://([^/:?]+).*$\\\" .url \\\"$1\\\"}}\"\n      | station !~ \"ocremix.org|lidarr\"\n      | station != \"\"\n    [$__auto])\n  )\n)"
    }
   ]
  },
  {
   "title": "Music Now Playing (LyrionMusicServer)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\"(?i)(lyrionmusicserver|lms)\"} |= \"currently playing\""
    }
   ]
  }
 ]
}