{
 "title": "Webanalytics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Resource Impressions by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({host=\"localhost\"} | json | keep DownstreamStatus [1m])",
     "legendFormat": "{{DownstreamStatus}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{host=\"localhost\"} | json | line_format \"{{.ClientHost}} {{.DownstreamStatus}} {{.RequestHost}} {{.RequestMethod}} {{.RequestPath}} {{.OS}} {{.Browser}} {{.Device}} {{.geoip_country_name}} {{.request_User_Agent}}\""
    }
   ]
  },
  {
   "title": "Pages Count",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (request_path)(count_over_time({host=\"localhost\"} | json [$__auto]))"
    }
   ]
  },
  {
   "title": "Access Map",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 15, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "{host= \"localhost\"} | json "
    }
   ]
  },
  {
   "title": "Count by Browser",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (Browser) (\n    count_over_time(\n        {host=\"localhost\"} \n        | json    | Browser != \"\" \n        | label_format Browser=`{{ regexReplaceAll \"[/ ].*$\" .Browser \"$1\" }}`\n        | keep Browser \n        [$__auto]\n    )\n)"
    }
   ]
  },
  {
   "title": "Count by Browser",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 10, "x": 5, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (Browser) (\n    count_over_time(\n        {host=\"localhost\"} \n        | json   | Browser != \"\" \n        | label_format Browser=`{{ regexReplaceAll \"[/ ].*$\" .Browser \"$1\" }}`\n        | keep Browser \n        [$__auto]\n    )\n)",
     "legendFormat": "{{Browser}}"
    }
   ]
  },
  {
   "title": "Count by OS",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (OS) (\n    count_over_time(\n        {host=\"localhost\"} \n        | json    | OS != \"\" \n        | keep OS \n        [$__auto]\n    )\n)",
     "legendFormat": "{{OS}}"
    }
   ]
  },
  {
   "title": "Count by Country",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (geoip_country_name) (\n    count_over_time(\n        {host=\"localhost\"} \n        | json    | geoip_country_name != \"\" \n        | keep geoip_country_name \n        [$__auto]\n    )\n)"
    }
   ]
  },
  {
   "title": "Count by Country",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 10, "x": 5, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (geoip_country_name) (\n    count_over_time(\n        {host=\"localhost\"} \n        | json      | geoip_country_name != \"\" \n        | keep geoip_country_name \n        [$__auto]\n    )\n)",
     "legendFormat": "{{geoip_country_name}}"
    }
   ]
  },
  {
   "title": "Unique Vistors",
   "type": "stat",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count_over_time({host=\"localhost\"} | json  | label_format ID=`{{.ClientHost}}{{.request_User_Agent}}` | keep ID [1d]))"
    }
   ]
  }
 ]
}